[package]
name = "rust-node-exporter"
version = "0.1.0"
authors = ["Darkhan Kubigenov <darkhanu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4.0"
serde_json = "1.0.59"
serde = { version = "1.0", features = [ "derive", "alloc" ] }
quick-xml = { version = "0.22", features = [ "serialize" ] }
hidapi = "1.2.6"

[profile.release]
lto = true
