[package]
name = "rust-node-exporter"
version = "0.1.0"
authors = ["Darkhan Kubigenov <darkhanu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "~2.33.0", features = ["yaml"]}
ctrlc = "3.1.9"
hidapi = "1.2.6"
lazy_static = "1.4.0"
quick-xml = { version = "0.22", features = [ "serialize" ] }
regex = "1"
serde = { version = "1.0", features = [ "derive", "alloc" ] }
serde_json = "1.0.59"

[build-dependencies]
bindgen = "0.58.1"

[profile.release]
lto = true
