[package]
name = "rust-node-exporter"
version = "0.2.1"
authors = ["Darkhan Kubigenov <darkhanu@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "~3.1.18", features = ["derive"]}
ctrlc = "3.1.9"
hidapi = "1.4.1"
lazy_static = "1.4.0"
quick-xml = { version = "0.22", features = [ "serialize" ] }
regex = "1"
serde = { version = "1.0", features = [ "derive", "alloc" ] }
serde_json = "1.0.81"

[build-dependencies]
bindgen = "0.59.2"

[profile.release]
lto = true
